### ISSUE TITLE
Android 7 correct glyph is only 1st one

### ISSUE THREAD

**Issue by elmodos** [Cypher01/Xglyph2#5] opened 2017-08-10 17:03 UTC
With latest Xposed and without ability to launch configuration interface I hack with XGlyph enabled and draw random items, repeatedly Ingress shows I enter correctly only 1st glyph in the sequence

**Comment by Cypher01** [comment] 2017-08-10 17:42
You have to understand, that I'm not very motivated to investigate in this problem, because the unofficial alpha version of Xposed for Nougat is uncomplete and very unstable.

I'm pretty sure that Xglyph² will work out of the box, when an official stable version of Xposed for Nougat is released. If not, I'm going to fix it as soon as I can.

You can find my full statement on [XDA](https://forum.xda-developers.com/showpost.php?p=73142598&postcount=113)

**Comment by elmodos** [comment] 2017-08-10 18:01
I guess anyways world readable preferences will have to be moved to some local file or so due to deprecation.

`		pref = getSharedPreferences(PREF, MODE_WORLD_READABLE);
`

> FATAL EXCEPTION: main MODE_WORLD_READABLE no longer supported

**Comment by Cypher01** [comment] 2017-08-12 02:16
Oh, interesting. I've fixed this, but I cannot guarantee that everything still works as expected.

[Post on XDA](https://forum.xda-developers.com/showpost.php?p=73370574&postcount=114)

**Comment by elmodos** [comment] 2017-08-12 11:10
Thanks for patch.
Back to issue title. Only 1st glyph is accepted as correct, others are not. 
I've rebooted device, started ingress and hacked with "more" command. 
Log:

> 08-12 13:50:01.000 I/Xposed  ( 3793): -----------------
> 08-12 13:50:01.000 I/Xposed  ( 3793): Starting Xposed version 88 (Xposed SDK25 Nougat ARM64 by PurifyOS), compiled for SDK 25
> 08-12 13:50:01.000 I/Xposed  ( 3793): Device: ONEPLUS A3003 (OnePlus), Android version 7.1.1 (SDK 25)
> 08-12 13:50:01.000 I/Xposed  ( 3793): ROM: ONEPLUS A3003_16_170527
> 08-12 13:50:01.019 I/Xposed  ( 3793): -----------------
> 
> 08-12 13:50:01.372 I/Xposed  ( 3793): Xglyph: [DEBUG] Preferences set world readable FAILED
> 
> 08-12 13:50:27.841 I/Xposed  ( 6456): Xglyph: [DEBUG] Ingress loaded
> 
> 08-12 13:56:34.601 I/Xposed  ( 6456): Xglyph: [DEBUG] PortalHackingParams: constructor for normal hack called
> 08-12 13:56:34.601 I/Xposed  ( 6456): Xglyph: [DEBUG] arg0 = 9cfbad2b76bb4bfca50354603abdc081.16, glyphGameRequested = true, hackNoKey = false
> 08-12 13:56:34.601 I/Xposed  ( 6456): Xglyph: [DEBUG] PortalHackingParams: constructor for normal hack called
> 08-12 13:56:34.601 I/Xposed  ( 6456): Xglyph: [DEBUG] arg0 = 9cfbad2b76bb4bfca50354603abdc081.16, glyphGameRequested = true, hackNoKey = false
> 08-12 13:56:35.788 I/Xposed  ( 6456): Xglyph: [DEBUG] com.nianticproject.ingress.common.utility.Turing.g called
> 08-12 13:56:35.788 I/Xposed  ( 6456): Xglyph: [DEBUG] parameter (param[0]): g0
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] glyph: hgjkih
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] sequence.size(): 1
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] com.nianticproject.ingress.common.utility.Turing.g called
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] parameter (param[0]): g0
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] glyph: ikjghi
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] sequence.size(): 2
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] com.nianticproject.ingress.common.utility.Turing.g called
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] parameter (param[0]): g1
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] glyph: kdejk
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] sequence.size(): 3
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] com.nianticproject.ingress.common.utility.Turing.g called
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] parameter (param[0]): g1
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] glyph: kdejk
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] sequence.size(): 4
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] com.nianticproject.ingress.common.utility.Turing.g called
> 08-12 13:56:35.795 I/Xposed  ( 6456): Xglyph: [DEBUG] parameter (param[0]): g2
> 08-12 13:56:35.796 I/Xposed  ( 6456): Xglyph: [DEBUG] glyph: jghij
> 08-12 13:56:35.796 I/Xposed  ( 6456): Xglyph: [DEBUG] sequence.size(): 5
> 08-12 13:56:35.796 I/Xposed  ( 6456): Xglyph: [DEBUG] com.nianticproject.ingress.common.utility.Turing.g called
> 08-12 13:56:35.796 I/Xposed  ( 6456): Xglyph: [DEBUG] parameter (param[0]): g2
> 08-12 13:56:35.796 I/Xposed  ( 6456): Xglyph: [DEBUG] glyph: jghij
> 08-12 13:56:35.796 I/Xposed  ( 6456): Xglyph: [DEBUG] sequence.size(): 6
> 08-12 13:56:35.796 I/Xposed  ( 6456): Xglyph: [DEBUG] com.nianticproject.ingress.common.utility.Turing.g called
> 08-12 13:56:35.796 I/Xposed  ( 6456): Xglyph: [DEBUG] parameter (param[0]): g3
> 08-12 13:56:35.796 I/Xposed  ( 6456): Xglyph: [DEBUG] glyph: jefgkicbh
> 08-12 13:56:35.796 I/Xposed  ( 6456): Xglyph: [DEBUG] sequence.size(): 7
> 08-12 13:56:35.796 I/Xposed  ( 6456): Xglyph: [DEBUG] com.nianticproject.ingress.common.utility.Turing.g called
> 08-12 13:56:35.796 I/Xposed  ( 6456): Xglyph: [DEBUG] parameter (param[0]): g3
> 08-12 13:56:35.797 I/Xposed  ( 6456): Xglyph: [DEBUG] glyph: jefgkicbh
> 08-12 13:56:35.797 I/Xposed  ( 6456): Xglyph: [DEBUG] sequence.size(): 8
> 08-12 13:56:35.894 I/Xposed  ( 6456): Xglyph: [DEBUG] o.nb.ˊ called
> 08-12 13:56:35.895 I/Xposed  ( 6456): Xglyph: [DEBUG] glyphString (param[0]): jki
> 08-12 13:56:35.895 I/Xposed  ( 6456): Xglyph: [DEBUG] Glyph Hack speed switched off
> 08-12 13:56:35.895 I/Xposed  ( 6456): Xglyph: [DEBUG] o.nb.ˊ called
> 08-12 13:56:35.895 I/Xposed  ( 6456): Xglyph: [DEBUG] glyphString (param[0]): jki
> 08-12 13:56:35.895 I/Xposed  ( 6456): Xglyph: [DEBUG] Glyph Hack speed switched off
> 08-12 13:56:48.816 I/Xposed  ( 6456): Xglyph: [DEBUG] PortalHackingParams: constructor for glyph hack called
> 08-12 13:56:48.818 I/Xposed  ( 6456): Xglyph: [DEBUG] original uigs1: UserInputGlyphSequence{glyphResponses=[Glyph{glyphOrder=}, Glyph{glyphOrder=j}, Glyph{glyphOrder=}, Glyph{glyphOrder=j}], bypassed=false, inputTimeMs=533}
> 08-12 13:56:48.818 I/Xposed  ( 6456): Xglyph: [DEBUG] bypassed: false
> 08-12 13:56:48.819 I/Xposed  ( 6456): Xglyph: [DEBUG] inputTimeMs = 533
> 08-12 13:56:48.826 I/Xposed  ( 6456): Xglyph: [DEBUG] original uigs2: UserInputGlyphSequence{glyphResponses=[Glyph{glyphOrder=jki}], bypassed=false, inputTimeMs=566}
> 08-12 13:56:48.827 I/Xposed  ( 6456): Xglyph: [DEBUG] bypassed: false
> 08-12 13:56:48.827 I/Xposed  ( 6456): Xglyph: [DEBUG] command glyph inputs: [jki]
> 08-12 13:56:48.827 I/Xposed  ( 6456): Xglyph: [DEBUG] Glyph Hack key request set (overridden)
> 08-12 13:56:48.827 I/Xposed  ( 6456): Xglyph: [DEBUG] Glyph Hack speed switched off
> 08-12 13:56:48.828 I/Xposed  ( 6456): Xglyph: [DEBUG] patched uigs1: UserInputGlyphSequence{glyphResponses=[Glyph{glyphOrder=hgjkih}, Glyph{glyphOrder=ikjghi}, Glyph{glyphOrder=kdejk}, Glyph{glyphOrder=kdejk}, Glyph{glyphOrder=jghij}, Glyph{glyphOrder=jghij}, Glyph{glyphOrder=jefgkicbh}, Glyph{glyphOrder=jefgkicbh}], bypassed=false, inputTimeMs=533}
> 08-12 13:56:48.828 I/Xposed  ( 6456): Xglyph: [DEBUG] patched uigs2: UserInputGlyphSequence{glyphResponses=[Glyph{glyphOrder=ikj}], bypassed=false, inputTimeMs=445}
> 08-12 13:56:48.828 I/Xposed  ( 6456): Xglyph: [DEBUG] PortalHackingParams: constructor for glyph hack called
> 08-12 13:56:48.830 I/Xposed  ( 6456): Xglyph: [DEBUG] original uigs1: UserInputGlyphSequence{glyphResponses=[Glyph{glyphOrder=hgjkih}, Glyph{glyphOrder=ikjghi}, Glyph{glyphOrder=kdejk}, Glyph{glyphOrder=kdejk}, Glyph{glyphOrder=jghij}, Glyph{glyphOrder=jghij}, Glyph{glyphOrder=jefgkicbh}, Glyph{glyphOrder=jefgkicbh}], bypassed=false, inputTimeMs=533}
> 08-12 13:56:48.830 I/Xposed  ( 6456): Xglyph: [DEBUG] bypassed: false
> 08-12 13:56:48.830 I/Xposed  ( 6456): Xglyph: [DEBUG] inputTimeMs = 533
> 08-12 13:56:48.832 I/Xposed  ( 6456): Xglyph: [DEBUG] original uigs2: UserInputGlyphSequence{glyphResponses=[Glyph{glyphOrder=ikj}], bypassed=false, inputTimeMs=445}
> 08-12 13:56:48.832 I/Xposed  ( 6456): Xglyph: [DEBUG] bypassed: false
> 08-12 13:56:48.833 I/Xposed  ( 6456): Xglyph: [DEBUG] command glyph inputs: [ikj]
> 08-12 13:56:48.833 I/Xposed  ( 6456): Xglyph: [DEBUG] Glyph Hack key request set (overridden)
> 08-12 13:56:48.833 I/Xposed  ( 6456): Xglyph: [DEBUG] Glyph Hack speed switched off
> 08-12 13:56:48.834 I/Xposed  ( 6456): Xglyph: [DEBUG] patched uigs1: UserInputGlyphSequence{glyphResponses=[Glyph{glyphOrder=hgjkih}, Glyph{glyphOrder=ikjghi}, Glyph{glyphOrder=kdejk}, Glyph{glyphOrder=kdejk}, Glyph{glyphOrder=jghij}, Glyph{glyphOrder=jghij}, Glyph{glyphOrder=jefgkicbh}, Glyph{glyphOrder=jefgkicbh}], bypassed=false, inputTimeMs=533}
> 08-12 13:56:48.834 I/Xposed  ( 6456): Xglyph: [DEBUG] patched uigs2: UserInputGlyphSequence{glyphResponses=[Glyph{glyphOrder=ikj}], bypassed=false, inputTimeMs=401}
> 08-12 13:56:50.264 I/Xposed  ( 6456): Xglyph: [DEBUG] com.nianticproject.ingress.common.utility.Turing.l called
> 08-12 13:56:50.264 I/Xposed  ( 6456): Xglyph: [DEBUG] com.nianticproject.ingress.common.utility.Turing.l called
>

**Comment by Cypher01** [comment] 2017-08-12 13:41
Hm, strange. I cannot confirm this on Marshmallow. At least [one post on XDA](https://forum.xda-developers.com/showpost.php?p=73373134&postcount=115) confirms that it works.

I guess this is because of bugs in Xposed. They say, hooking methods is unreliable and not executed everytime.

Maybe you should also post this in the XDA thread, let's see if someone else faces this problem.

**Comment by zijianwang90** [comment] 2017-10-09 08:18
Official Xposed v88 is out, still have this problem.

**Comment by pahanstr** [comment] 2017-10-15 21:57
+ solve the problem! and I'm ready to donate for autogliph

**Comment by elmodos** [comment] 2017-10-16 01:43
@pahanstr  Maybe this info will be useful:
1. launch ingress
2. hack and see only 1st glyph is shown as correct
3. close ingress and run it again
4. now glyph hack works as expected

@Cypher01 can it be a reason that reload of app reinitializes xglyph, what is not done at initial load? I am not java dev, so leaving question open up to you.

**Comment by Cypher01** [comment] 2017-10-20 22:49
I cannot reproduce the problem. But I still think, this is caused by a bug in Xposed.

Xglyph² does the following:

- For every incoming glyph, a method is hooked to record the glyph and store it in a list in the GlyphTranslator class. So for example for 5 glyphs this is done 5 times independently.
- This list is used to build the data, that is going to be sent back to the server.
- After the glyph game, a method is called. This is also hooked to clear the list. This is important, because Xglyph² cannot distinguish between recently and previously recorded glyphs.

In @elmodos' log, one can see, that a package of 8 glyphs is sent back. This looks like the second hook for clearing the list didn't work.

So yeah, this looks like the unreliable method hooking I already mentioned.

In the meantime, official Xposed has been updated to v88.1. I suggest to try to reinstall Xposed, maybe first remove it, reboot, and install it again.

**Comment by zijianwang90** [comment] 2017-10-23 09:11
This issue happened on me after I flashed official xposed on top of unofficial one. Now I've completely re-flash my rom and xposed, everything is working great again! 😁

**Comment by Cypher01** [comment] 2017-10-24 00:30
OK, great!

So @zijianwang90's report confirms, this is not a problem of Xglyph², but Xposed.

So I'm closing this issue.

**Closed as completed by Cypher01** 2017-10-24 00:30 UTC
